# Generated by Django 4.2.3 on 2023-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api01", "0003_session_agent_session_ip_session_referer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="agent",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="ip",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="referer",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
